### ISSUE TITLE
Remove locals

### ISSUE THREAD

**Issue by IanaKhitsko** [akrava/software-engineering-methodology-practices#2]
https://github.com/akrava/software-engineering-methodology-practices/blob/fe840e69c81350029521012809f3327be4ba95f4/practice1/eurodiffusion/eurodiffusion.go#L24

it seems that offset* are used only once, remove them

**Comment by akrava** [comment]
Thanks for finding this defect. I agree that we need to make some enhancements in order to remove locals

**Comment by akrava** [comment]
I've opened PR #7 in order to merge enhancement and fix this issue.

**Comment by akrava** [comment]
Fixed in https://github.com/akrava/software-engineering-methodology-practices/commit/1aa7ba975aba74f14b7d0453315ede72ea32ddba. So this issue is closed. Feel free to reopen if needed
