### ISSUE TITLE
Too many nesting levels

### ISSUE THREAD

**Issue by IanaKhitsko** [akrava/software-engineering-methodology-practices#3]
https://github.com/akrava/software-engineering-methodology-practices/blob/fe840e69c81350029521012809f3327be4ba95f4/practice1/eurodiffusion/eurodiffusion.go#L42

Consider to make the code more "linear". E.g., you can make here  "if (city == nil) continue;"

**Comment by akrava** [comment]
Agree, it's looking too complicated now. I'll reduce nested levels in this function. Thanks

**Comment by akrava** [comment]
In order to fix this issue I've opened PR #8. I'll merge it

**Comment by akrava** [comment]
Fixed in https://github.com/akrava/software-engineering-methodology-practices/commit/1d6e97620ca680aa6e5181713f25d425ec5f2787. Issue is closed, feel free to reopen if needed
