### ISSUE TITLE
Attribute name 

### ISSUE THREAD

**Issue by IanaKhitsko** [akrava/software-engineering-methodology-practices#4]
https://github.com/akrava/software-engineering-methodology-practices/blob/fe840e69c81350029521012809f3327be4ba95f4/practice1/eurodiffusion/eurodiffusion.go#L82

IsCompleated -> IsCompleted

**Comment by akrava** [comment]
Thanks for finding this typo. I'll fix it

**Comment by akrava** [comment]
I've opened PR #9 in order to fix typo and merge changes.

**Comment by akrava** [comment]
Fixed in https://github.com/akrava/software-engineering-methodology-practices/commit/17cc50cbe718095aecafd952dc96ffc11b20f1f1. So issue is closed. Feel free to reopen if needed
