### ISSUE TITLE
Levels number again

### ISSUE THREAD

**Issue by IanaKhitsko** [akrava/software-engineering-methodology-practices#5]
https://github.com/akrava/software-engineering-methodology-practices/blob/fe840e69c81350029521012809f3327be4ba95f4/practice1/eurodiffusion/eurodiffusion.go#L113

if (cityTo == nil) return;

**Comment by akrava** [comment]
Agree, we can reduce levels number in this function too in order to make code more readable. I'll do it, thanks

**Comment by akrava** [comment]
In order to resolve this issue I've created PR #10. I'm going to merge it.

**Comment by akrava** [comment]
Fixed in https://github.com/akrava/software-engineering-methodology-practices/commit/2e7fff036e80c99f5bfc2b96b5a6d63442c5aca3. Issue is closed, feel free to reopen if needed
