### ISSUE TITLE
City coordinates min and max

### ISSUE THREAD

**Issue by IanaKhitsko** [akrava/software-engineering-methodology-practices#6]
https://github.com/akrava/software-engineering-methodology-practices/blob/fe840e69c81350029521012809f3327be4ba95f4/practice1/eurodiffusion/eurodiffusion.go#L125

1<=x,y<=10

**Comment by akrava** [comment]
Good catch, thanks! I've forgotten to use here input data limitations. I'll fix it

**Comment by akrava** [comment]
I've opened PR #11 in order to enhance code by resolving this issue.

**Comment by akrava** [comment]
Fixed in https://github.com/akrava/software-engineering-methodology-practices/commit/81e9e70db90115bac972b71d86090824a13f0ab6. So this issue is closed. Feel free to reopen if needed
